server:
  port: 8888
  tomcat:
    uri-encoding: utf-8

spring:

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
      name:
      username: root
      password:


swagger2:
  defaultGroupName: "defaultGroupName"
  defaultBasePackage: "com.company.project.controller"
  defaultTitle: "defaultTitle"
  defaultDescription: "defaultDescription"
  defaultTermsOfServiceUrl: "{host}/doc.html"
  defaultVersion: "defaultVersion"



